### ISSUE TITLE
Cannot run `yarn standalone`

### ISSUE THREAD

**Issue by benoitguigal** [konnectors/cozy-konnector-template#176]
## Steps to reproduce
```
git clone https://github.com/konnectors/cozy-konnector-template cozy-konnector-newservice
cd cozy-konnector-newservice
rm -rf .git
git init
yarn install 
yarn standalone
```

throws 

```
TypeError: Cannot read property 'folderPath' of undefined
@ ./node_modules/cozy-konnector-libs/dist/helpers/cozy-client-js-stub.js:171
    DUMP_PATH = path.join(KONNECTOR_DEV_CONFIG.fields.folderPath || rootPath, DUMP_PATH);
```

## Configuration 
yarn 1.12.3
macOS Mojave 
cozy-connector-template@4854003cad50a1338dc3ba3d93f8b15d4974b851

**Comment by doubleface** [comment]
I can reproduce it. This is a regression in cozy-konnector-libs. A new version will be out shortly. Thanks for the report @benoitguigal :+1:

**Comment by doubleface** [comment]
@benoitguigal You can use cozy-konnector-libs@4.11.3 to make it work as expected. 4.11.5 is on it's way.
