### ISSUE TITLE
Supprimer la commande yarn deploy:prod

### ISSUE THREAD

**Issue by kosssi** [konnectors/cozy-konnector-template#40]
On pourrait optimiser les commandes de déploiements, dans le fichier `pachage.json`il y a actuellement ceci :

```
"deploy": "git-directory-deploy --directory build/ --branch build --repo=${DEPLOY_REPOSITORY:-https://$GITHUB_TOKEN@github.com/konnectors/cozy-konnector-nef.git}",
"deploy:prod": "git-directory-deploy --directory build/ --branch prod --repo=${DEPLOY_REPOSITORY:-https://$GITHUB_TOKEN@github.com/konnectors/cozy-konnector-nef.git}",
```

Les  2 commandes sont vraiment identiques, avec seulement un nom de branche qui change...

Je proposerai bien d'avoir une seul commande:

```
"deploy": "git-directory-deploy --directory build/ --branch=${DEPLOY_BRANCH:-build} --repo=${DEPLOY_REPOSITORY:-https://$GITHUB_TOKEN@github.com/konnectors/cozy-konnector-nef.git}"
```

Ca veut dire que l'on doit changer `package.json` et `.travis.yml`.

Vous en pensez quoi ?

**Comment by ptbrowne** [comment]
👍

**Comment by drazik** [comment]
La variable `DEPLOY_BRANCH` est passée à Travis selon la branche sur laquelle il est en train de build ? master => build et prod => latest ?

**Comment by kosssi** [comment]
tout a fait @drazik 
- vu que `build` est la branche par défaut je n'ai pas fait de modification coté travis.
- par contre pour la branche `latest` tu peux voir les changements ici https://github.com/konnectors/cozy-konnector-template/pull/43/files#diff-354f30a63fb0907d4ad57269548329e3R26

**Comment by drazik** [comment]
OK nice :+1:

**Comment by kosssi** [comment]
https://github.com/konnectors/cozy-konnector-template/pull/43
