### ISSUE TITLE
Change CODEOWNERS file

### ISSUE THREAD

**Issue by enguerran** [konnectors/cozy-konnector-template#92]
As mentioned here: [https://help.github.com/articles/about-codeowners/](https://help.github.com/articles/about-codeowners/) this file is used to automatically set reviewers in a PR.
Today this file list a certain number of developers and it is hard to maintain.
If we set it to the @konnectors/maintainers team, it will be easier to maintain the members list automatically added as reviewers, etc.

**Comment by doubleface** [comment]
Despite the documentation,  @konnectors/maintainers as CODEOWNERS does not seem to work
