### ISSUE TITLE
Jest with es6 files should work by default

### ISSUE THREAD

**Issue by ptbrowne** [konnectors/cozy-konnector-template#95]
https://facebook.github.io/jest/docs/en/getting-started.html#additional-configuration

`.babelrc`

```
{
  "presets": ["env", "react"]
}
```

```
yarn add -D babel-preset-react babel-jest babel-core regenerator-runtime
```

**Comment by enguerran** [comment]
Hi @ptbrowne 
Thank you for opening an issue but I don't understand what do you mean by "es6 files should work by default"?

First of all, there is no `jest` in the template. However `jest` is included in [http://www.github.com/konnectors/libs](http://www.github.com/konnectors/libs).
AFAIK I could write something like this and run `yarn jest` in a fresh clone of this [http://www.github.com/konnectors/cozy-konnector-template](http://www.github.com/konnectors/cozy-konnector-template):

```js
describe('Hello test', () => {
  test('check 1+1', () => {
    expect(1 + 1).toBe(2)
  })

  test('destructuring', () => {
    const fruits = ['apple', 'strawberry', 'banana']
    const [apple, ...others] = fruits
    expect(apple).toBe('apple')
    expect(others).toHaveLength(2)
  })
})
```

Moreover, why would you add `babel-preset-react` as there is no `react` involved in the template: this code must be pure `nodejs` code.

**Comment by ptbrowne** [comment]
> Moreover, why would you add babel-preset-react as there is no react involved in the template: this code must be pure nodejs code.

I made a mistake :) I was `import`ing in the jest tests and forgot we were in node context 👍
